import { NextRequest, NextResponse } from "next/server";

/**
 * Attribution cookie capture — the middleware-free replacement.
 *
 * `proxy.ts` used to write these cookies on any request whose URL carried the
 * matching query params. That middleware is disabled on Netlify (Next 16
 * middleware can't be edge-bundled by the adapter), which silently broke
 * attribution: `campaigns/actions.ts` reads `embed_ref` and `auth/actions.ts`
 * reads `invite_ref`, so every invite signup and partner-widget action since
 * the migration has gone uncredited.
 *
 * Rebuilt as a route handler because a Server Component cannot set cookies —
 * only route handlers and server actions can. The client island
 * `AttributionCapture` calls this once per landing that carries params.
 *
 * The cookies stay **httpOnly**: they're set here, server-side, exactly as the
 * middleware set them. The client only reports which params it saw; it never
 * holds the cookie value. That preserves the original trust properties.
 *
 * Validation accepts exactly what the middleware accepted and nothing more — a
 * bad host or code is dropped, never stored. That parity is the point: a
 * validator here that is tighter than the one in the middleware does not fail
 * loudly, it just silently credits nobody. That is what happened to partner QR
 * codes between 2026-07-26 and this fix, so each rule below names the producer
 * it has to accept.
 */

const EMBED_REF_COOKIE = "embed_ref";
// 60 days, as the middleware set it and as docs/GLOSSARY.md documents. A shop
// hands out a poster once; the credit window has to outlast the visit.
const EMBED_REF_TTL_DAYS = 60;
const LANDING_STATE_COOKIE = "landing_state";
const LANDING_STATE_TTL_DAYS = 30;
const INVITE_REF_COOKIE = "invite_ref";
const INVITE_REF_TTL_DAYS = 30;

// The `host` param carries one of two things, and BOTH must be accepted:
//   - an embedding site's hostname, from the widget (window.location.hostname)
//   - a partner SLUG, from a printed QR code — `partnerQrUrl()` writes
//     ?host=<slug>, and migration 0043 constrains a slug to ^[a-z0-9-]{1,80}$,
//     which has no dot in it
// Requiring a dot here rejected every partner slug, so every QR scan since the
// middleware was replaced set no cookie and credited nobody. Dot-separated
// labels, one or more — a single label is a slug, several are a hostname.
// No scheme, no path, no port.
//
// This is attribution, not authorisation: anyone can put a partner's slug in a
// URL and inflate that partner's counters. That was equally true of the
// middleware, and a slug is public — it is printed on the poster.
const HOST_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/;
const HOST_MAX = 80; // the slug constraint's cap, and the widget's own slice
// Two-letter state, or FED — which is what the embed widget sends by default
// (`data-state` defaults to "FED"), and what `consumeLandingState()` in
// auth/actions.ts already validates against on the read side.
const STATE_RE = /^([A-Z]{2}|FED)$/;
// Matches the codes generated by the profiles.invite_code trigger (mig 0102),
// and the same bound the /i/[code] shortlink validates before redirecting.
const INVITE_CODE_RE = /^[a-z0-9]{4,32}$/;

const COOKIE_BASE = {
  path: "/",
  httpOnly: true,
  secure: process.env.NODE_ENV === "production",
  sameSite: "lax",
} as const;

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  let body: { ref?: string; host?: string; state?: string; via?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false }, { status: 400 });
  }

  const res = NextResponse.json({ ok: true });
  const set: string[] = [];

  // Partner embed widget: ?ref=embed&host=<hostname>
  const host = typeof body.host === "string" ? body.host.toLowerCase() : "";
  if (body.ref === "embed" && host && host.length <= HOST_MAX && HOST_RE.test(host)) {
    res.cookies.set(EMBED_REF_COOKIE, host, { ...COOKIE_BASE, maxAge: EMBED_REF_TTL_DAYS * 86400 });
    set.push(EMBED_REF_COOKIE);
  }

  // State code from an embed link OR a direct share — used by signIn/signUp to
  // route a new user to a matched campaign instead of the default /dashboard.
  const state = typeof body.state === "string" ? body.state.toUpperCase() : "";
  if (state && STATE_RE.test(state)) {
    res.cookies.set(LANDING_STATE_COOKIE, state, { ...COOKIE_BASE, maxAge: LANDING_STATE_TTL_DAYS * 86400 });
    set.push(LANDING_STATE_COOKIE);
  }

  // Invite: ?via=CODE (the /i/CODE shortlink redirects into this same form).
  // Read by signUp to link the new account to its inviter via the
  // record_invite_redemption RPC. 30-day TTL — long enough for "saw the link,
  // signed up later", short enough that one share doesn't credit forever.
  const via = typeof body.via === "string" ? body.via.toLowerCase() : "";
  if (via && INVITE_CODE_RE.test(via)) {
    res.cookies.set(INVITE_REF_COOKIE, via, { ...COOKIE_BASE, maxAge: INVITE_REF_TTL_DAYS * 86400 });
    set.push(INVITE_REF_COOKIE);
  }

  return NextResponse.json({ ok: true, set }, { headers: res.headers });
}
