import { NextRequest, NextResponse } from "next/server";

/**
 * Attribution cookie capture — the middleware-free replacement.
 *
 * `proxy.ts` used to write these cookies on any request whose URL carried the
 * matching query params. That middleware is disabled on Netlify (Next 16
 * middleware can't be edge-bundled by the adapter), which silently broke
 * attribution: `campaigns/actions.ts` reads `embed_ref` and `auth/actions.ts`
 * reads `invite_ref`, so every invite signup and partner-widget action since
 * the migration has gone uncredited.
 *
 * Rebuilt as a route handler because a Server Component cannot set cookies —
 * only route handlers and server actions can. The client island
 * `AttributionCapture` calls this once per landing that carries params.
 *
 * The cookies stay **httpOnly**: they're set here, server-side, exactly as the
 * middleware set them. The client only reports which params it saw; it never
 * holds the cookie value. That preserves the original trust properties.
 *
 * Validation is deliberately identical to the middleware's — a bad host or
 * code is dropped, never stored.
 */

const EMBED_REF_COOKIE = "embed_ref";
const EMBED_REF_TTL_DAYS = 30;
const LANDING_STATE_COOKIE = "landing_state";
const LANDING_STATE_TTL_DAYS = 30;
const INVITE_REF_COOKIE = "invite_ref";
const INVITE_REF_TTL_DAYS = 30;

// A bare hostname: labels separated by dots. No scheme, no path, no port —
// anything else is not a partner host and must not be persisted.
const HOST_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;
const STATE_RE = /^[A-Z]{2}$/;
// Matches the codes generated by the profiles.invite_code trigger (mig 0102).
const INVITE_CODE_RE = /^[a-z0-9]{4,16}$/;

const COOKIE_BASE = {
  path: "/",
  httpOnly: true,
  secure: process.env.NODE_ENV === "production",
  sameSite: "lax",
} as const;

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  let body: { ref?: string; host?: string; state?: string; via?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false }, { status: 400 });
  }

  const res = NextResponse.json({ ok: true });
  const set: string[] = [];

  // Partner embed widget: ?ref=embed&host=<hostname>
  const host = typeof body.host === "string" ? body.host.toLowerCase() : "";
  if (body.ref === "embed" && host && HOST_RE.test(host)) {
    res.cookies.set(EMBED_REF_COOKIE, host, { ...COOKIE_BASE, maxAge: EMBED_REF_TTL_DAYS * 86400 });
    set.push(EMBED_REF_COOKIE);
  }

  // State code from an embed link OR a direct share — used by signIn/signUp to
  // route a new user to a matched campaign instead of the default /dashboard.
  const state = typeof body.state === "string" ? body.state.toUpperCase() : "";
  if (state && STATE_RE.test(state)) {
    res.cookies.set(LANDING_STATE_COOKIE, state, { ...COOKIE_BASE, maxAge: LANDING_STATE_TTL_DAYS * 86400 });
    set.push(LANDING_STATE_COOKIE);
  }

  // Invite: ?via=CODE (the /i/CODE shortlink redirects into this same form).
  // Read by signUp to link the new account to its inviter via the
  // record_invite_redemption RPC. 30-day TTL — long enough for "saw the link,
  // signed up later", short enough that one share doesn't credit forever.
  const via = typeof body.via === "string" ? body.via.toLowerCase() : "";
  if (via && INVITE_CODE_RE.test(via)) {
    res.cookies.set(INVITE_REF_COOKIE, via, { ...COOKIE_BASE, maxAge: INVITE_REF_TTL_DAYS * 86400 });
    set.push(INVITE_REF_COOKIE);
  }

  return NextResponse.json({ ok: true, set }, { headers: res.headers });
}
