/**
 * Auto-generate "respond to this bill" campaigns from newly-detected
 * anti-kratom bills. Called from the daily cron after the bills sync
 * completes.
 *
 * Eligibility for auto-campaign:
 *   - bill.active = true
 *   - bill.state IS NOT NULL (federal handled separately later)
 *   - bill.kratom_relevance = 'anti'
 *   - bill.relevance_confidence >= 0.6  (only confident classifications;
 *       default for non-AI-enriched bills is null and these are skipped —
 *       they'll be picked up after enrichment runs locally)
 *   - bill.status NOT IN ('enacted', 'dead')
 *   - no existing campaign already linked via bill_id (auto OR manual)
 *
 * Templates: standardized "I'm a constituent, please vote NO" letter with
 * {{full_name}} / {{legislator_name}} / {{state}} placeholders. The bill's
 * advocacy_callout (Ollama-generated) is woven into the blurb + body for
 * specificity.
 *
 * Notifications: the existing `trg_campaign_notify` Postgres trigger fires
 * on campaign INSERT and fans out in-app notifications respecting each
 * user's preferences. We don't need to do that here.
 */

import type { SupabaseClient } from "@supabase/supabase-js";

type Bill = {
  id: string;
  state: string;
  bill_number: string;
  title: string | null;
  summary_ai: string | null;
  summary: string | null;
  advocacy_callout: string | null;
  kratom_relevance: string | null;
  relevance_confidence: number | null;
  status: string | null;
  last_action: string | null;
};

const slugify = (s: string): string =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);

function buildCampaign(bill: Bill) {
  const stateLc = bill.state.toLowerCase();
  const numLc = (bill.bill_number || "").toLowerCase().replace(/[^a-z0-9]/g, "");
  const slug = `stop-${stateLc}-${numLc || slugify(bill.title ?? "bill")}`.slice(0, 80);

  const shortTitle = (bill.title ?? "an anti-kratom bill").slice(0, 100);
  const title = `Stop ${bill.state} ${bill.bill_number}: ${shortTitle}`.slice(0, 200);

  const blurb =
    bill.advocacy_callout ??
    `An anti-kratom bill is moving in ${bill.state}. Email your state legislators today.`;

  const summaryLine = bill.summary_ai || bill.summary || "";
  const calloutLine = bill.advocacy_callout
    ? `\n\nWhy this matters: ${bill.advocacy_callout}`
    : "";

  const body_md =
    `${bill.state} ${bill.bill_number} ${bill.title ? `— "${bill.title}"` : ""} would harm ` +
    `the kratom community. ${summaryLine}${calloutLine}\n\n` +
    `Last action: ${bill.last_action ?? "(see source)"}\n\n` +
    `This campaign was auto-generated by iKratom's bill-tracker. Review and ` +
    `edit before sending — your personal story is what makes legislator emails ` +
    `actually get read.`;

  const subject_template =
    `Please oppose ${bill.bill_number} — kratom matters to your constituents`;

  const body_template =
    `Dear {{legislator_name}},\n\n` +
    `My name is {{full_name}} and I'm a constituent in ${bill.state}. I'm writing about ${bill.bill_number}, ${shortTitle}.\n\n` +
    (bill.advocacy_callout
      ? `${bill.advocacy_callout}\n\n`
      : `This bill would significantly restrict kratom access for adults in our state.\n\n`) +
    `Kratom is a botanical that millions of Americans use safely as part of their daily wellness — for managing chronic pain, anxiety, energy, and recovery from opioid dependence. Restrictive legislation pushes consumers toward unregulated sources and worsens the very public-health concerns it claims to address.\n\n` +
    `I respectfully ask you to vote NO on ${bill.bill_number}, or to support amendments that focus on consumer-protection standards (age limits, labeling, lab testing) rather than prohibition.\n\n` +
    `Thank you for representing us.\n\n` +
    `{{full_name}}\n` +
    `{{city}}, ${bill.state}`;

  return {
    slug,
    title,
    blurb: blurb.slice(0, 500),
    body_md: body_md.slice(0, 20000),
    state: bill.state,
    bill_id: bill.id,
    target_roles: ["state_senate", "state_house"],
    subject_template: subject_template.slice(0, 200),
    body_template: body_template.slice(0, 20000),
    active: true,
    auto_generated: true,
  };
}

export type AutoCreateResult = {
  considered: number;
  created: number;
  skippedExisting: number;
  errors: { bill_id: string; reason: string }[];
};

export async function autoCreateCampaignsForNewAntiBills(
  supabase: SupabaseClient,
): Promise<AutoCreateResult> {
  const result: AutoCreateResult = {
    considered: 0,
    created: 0,
    skippedExisting: 0,
    errors: [],
  };

  // Eligible bills
  const { data: billsRaw, error: billsErr } = await supabase
    .from("bills")
    .select(
      "id, state, bill_number, title, summary_ai, summary, advocacy_callout, " +
      "kratom_relevance, relevance_confidence, status, last_action",
    )
    .eq("active", true)
    .eq("kratom_relevance", "anti")
    .gte("relevance_confidence", 0.6)
    .not("state", "is", null)
    .not("status", "in", "(enacted,dead)");

  if (billsErr) {
    result.errors.push({ bill_id: "(query)", reason: billsErr.message });
    return result;
  }

  const bills = (billsRaw ?? []) as unknown as Bill[];
  result.considered = bills.length;
  if (bills.length === 0) return result;

  // Find which bill_ids already have ANY campaign (auto or manual). We only
  // auto-create when no campaign exists at all — admins can still hand-write
  // a campaign for the same bill, which suppresses auto-creation.
  const billIds = bills.map((b) => b.id);
  const { data: existingCampaigns } = await supabase
    .from("campaigns")
    .select("bill_id")
    .in("bill_id", billIds);
  const taken = new Set(
    (existingCampaigns ?? [])
      .map((c: { bill_id: string | null }) => c.bill_id)
      .filter((x): x is string => !!x),
  );

  for (const bill of bills) {
    if (taken.has(bill.id)) {
      result.skippedExisting++;
      continue;
    }
    const row = buildCampaign(bill);
    const { error } = await supabase.from("campaigns").insert(row);
    if (error) {
      // Slug collision / unique-violation path — try a numeric suffix once
      if (error.code === "23505") {
        const altRow = { ...row, slug: `${row.slug}-${Date.now().toString(36)}`.slice(0, 80) };
        const { error: retryErr } = await supabase.from("campaigns").insert(altRow);
        if (retryErr) {
          result.errors.push({ bill_id: bill.id, reason: retryErr.message });
        } else {
          result.created++;
        }
      } else {
        result.errors.push({ bill_id: bill.id, reason: error.message });
      }
    } else {
      result.created++;
    }
  }

  return result;
}
