import type { MetadataRoute } from "next";
import { siteConfig } from "@/config/site.config";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: siteConfig.name,
    short_name: siteConfig.name,
    description: siteConfig.description,
    start_url: "/dashboard",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    orientation: "portrait-primary",
    categories: ["news", "politics", "social", "lifestyle"],
    icons: [
      {
        // Auto-generated by app/icon.tsx — Next.js serves it at /icon and scales for any browser-requested size
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
    shortcuts: [
      {
        name: "Active campaigns",
        short_name: "Campaigns",
        description: "One-click emails to your legislators",
        url: "/campaigns",
      },
      {
        name: "State forums",
        short_name: "Forum",
        description: "State-by-state advocate discussion",
        url: "/forum",
      },
      {
        name: "Messages",
        short_name: "DMs",
        description: "Encrypted direct messages",
        url: "/messages",
      },
    ],
  };
}
