#!/usr/bin/env node
/**
 * One-time build: fetch US state GeoJSON, project via Albers USA, emit SVG paths.
 * Run with: node scripts/build-us-map.mjs
 * Output: src/lib/us-map-paths.ts
 */

import { writeFileSync } from "node:fs";
import { geoAlbersUsa, geoPath } from "d3-geo";

const SRC = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json";

// FIPS state code → 2-letter abbr
const FIPS_TO_ABBR = {
  "01":"AL","02":"AK","04":"AZ","05":"AR","06":"CA","08":"CO","09":"CT","10":"DE",
  "11":"DC","12":"FL","13":"GA","15":"HI","16":"ID","17":"IL","18":"IN","19":"IA",
  "20":"KS","21":"KY","22":"LA","23":"ME","24":"MD","25":"MA","26":"MI","27":"MN",
  "28":"MS","29":"MO","30":"MT","31":"NE","32":"NV","33":"NH","34":"NJ","35":"NM",
  "36":"NY","37":"NC","38":"ND","39":"OH","40":"OK","41":"OR","42":"PA","44":"RI",
  "45":"SC","46":"SD","47":"TN","48":"TX","49":"UT","50":"VT","51":"VA","53":"WA",
  "54":"WV","55":"WI","56":"WY",
};

console.log("Fetching GeoJSON…");
const res = await fetch(SRC);
const fc = await res.json();

// Project at 960×600 viewBox with Albers USA
const projection = geoAlbersUsa().scale(1100).translate([480, 290]);
const path = geoPath(projection);

/**
 * Strip bogus subpaths. Virginia's source geometry has 3 problems:
 *   1) An outer ring spanning the whole viewBox (the "grey overlay" bug)
 *   2) Small subpaths in unrelated map locations (likely AK/HI inset bleed)
 * We keep only:
 *   - subpaths starting inside the viewBox
 *   - subpaths within 80px of the LARGEST subpath's starting point (real
 *     state geometry stays close together — true islands like the Aleutians
 *     are far enough we drop them, but those belong to AK's feature anyway)
 */
function stripBogusSubpaths(d) {
  const parts = d.split(/(?=M)/).filter(Boolean);
  if (parts.length === 0) return d;

  // First filter: out-of-viewBox
  let kept = parts.filter((sub) => {
    const m = sub.match(/^M(-?[\d.]+),(-?[\d.]+)/);
    if (!m) return true;
    const x = parseFloat(m[1]);
    const y = parseFloat(m[2]);
    return x >= -5 && x <= 965 && y >= -5 && y <= 605;
  });
  if (kept.length === 0) return d;

  // Find the largest subpath (by string length — proxy for vertex count)
  let main = kept[0];
  for (const sub of kept) if (sub.length > main.length) main = sub;
  const mainStart = main.match(/^M(-?[\d.]+),(-?[\d.]+)/);
  if (!mainStart) return kept.join("");
  const mx = parseFloat(mainStart[1]);
  const my = parseFloat(mainStart[2]);

  // Second filter: drop tiny subpaths far from the main outline
  // Threshold: start point must be within 80px of main's start (state-scale distances)
  kept = kept.filter((sub) => {
    if (sub === main) return true;
    const m = sub.match(/^M(-?[\d.]+),(-?[\d.]+)/);
    if (!m) return true;
    const x = parseFloat(m[1]);
    const y = parseFloat(m[2]);
    const dx = x - mx;
    const dy = y - my;
    const dist = Math.sqrt(dx * dx + dy * dy);
    // Big subpaths are kept regardless (they're real)
    if (sub.length > 200) return true;
    return dist <= 80;
  });

  return kept.join("");
}

const out = [];
for (const f of fc.features) {
  const abbr = FIPS_TO_ABBR[f.id];
  if (!abbr) continue;
  const dRaw = path(f);
  if (!dRaw) continue;
  const d = stripBogusSubpaths(dRaw);
  if (!d) continue;
  out.push({ abbr, name: f.properties.name, d });
}

out.sort((a, b) => a.abbr.localeCompare(b.abbr));

const file = `// AUTO-GENERATED by scripts/build-us-map.mjs — do not edit by hand.
// Albers USA projection at viewBox 0 0 960 600.

export type StatePath = { abbr: string; name: string; d: string };

export const US_VIEWBOX = "0 0 960 600";

export const US_STATE_PATHS: StatePath[] = ${JSON.stringify(out, null, 2)};
`;

writeFileSync("src/lib/us-map-paths.ts", file);
console.log(`Wrote ${out.length} state paths to src/lib/us-map-paths.ts`);
