#!/usr/bin/env node
/**
 * Dump the current Supabase schema to docs/SCHEMA.md.
 *
 * Output: a structured markdown reference of every public table, view,
 * function, trigger, RLS policy, and index. Regenerate after every
 * migration.
 *
 *   npm run docs:schema
 *
 * Reads SUPABASE_ACCESS_TOKEN + SUPABASE_PROJECT_REF from .env.local.
 * Hits the Supabase Management API; no service-role key needed.
 *
 * Why a markdown dump and not just "look at the migrations":
 *   - Migrations show change-over-time, not the current state. After 43
 *     migrations, reconstructing "what does the profiles table look like
 *     right now" is a multi-file scavenger hunt.
 *   - AI agents can grep the markdown in seconds vs scanning 40+ SQL files.
 *   - Diffs between schema dumps in git history are themselves a useful
 *     change log.
 */

import { writeFileSync } from "node:fs";

const TOKEN = process.env.SUPABASE_ACCESS_TOKEN;
const REF = process.env.SUPABASE_PROJECT_REF;
const OUT = "docs/SCHEMA.md";

if (!TOKEN || !REF) {
  console.error("Missing SUPABASE_ACCESS_TOKEN or SUPABASE_PROJECT_REF");
  process.exit(1);
}

async function q(sql) {
  const r = await fetch(`https://api.supabase.com/v1/projects/${REF}/database/query`, {
    method: "POST",
    headers: { Authorization: `Bearer ${TOKEN}`, "Content-Type": "application/json" },
    body: JSON.stringify({ query: sql }),
  });
  if (!r.ok) throw new Error(`${r.status}: ${await r.text()}`);
  return r.json();
}

function esc(s) {
  if (s == null) return "";
  return String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

const out = [];

out.push("# Schema reference\n");
out.push(`> Auto-generated by \`npm run docs:schema\` on ${new Date().toISOString()}.`);
out.push("> **Do not hand-edit.** Re-run the script after migrations.\n");

// ── Tables + columns ──────────────────────────────────────────────
console.log("Tables...");
const tables = await q(`
  select t.table_name,
         obj_description(c.oid, 'pg_class') as comment
    from information_schema.tables t
    join pg_class c on c.relname = t.table_name
    join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
   where t.table_schema = 'public' and t.table_type = 'BASE TABLE'
     and t.table_name not like '\\_%'
     and t.table_name != '_ikratom_migrations'
   order by t.table_name
`);

out.push("\n## Tables\n");
for (const t of tables) {
  out.push(`### \`${t.table_name}\``);
  if (t.comment) out.push(`> ${t.comment}\n`);
  const cols = await q(`
    select column_name, data_type, is_nullable, column_default
      from information_schema.columns
     where table_schema='public' and table_name='${t.table_name}'
     order by ordinal_position
  `);
  out.push("| Column | Type | Nullable | Default |");
  out.push("|---|---|---|---|");
  for (const c of cols) {
    out.push(`| \`${esc(c.column_name)}\` | ${esc(c.data_type)} | ${c.is_nullable === "YES" ? "✓" : ""} | ${c.column_default ? `\`${esc(c.column_default)}\`` : ""} |`);
  }

  // RLS
  const rls = await q(`
    select policyname, cmd, roles, qual::text as using_expr, with_check::text as check_expr
      from pg_policies
     where schemaname='public' and tablename='${t.table_name}'
     order by cmd, policyname
  `);
  if (rls.length) {
    out.push("\n**RLS policies**");
    out.push("| Policy | Cmd | Roles | Using | With check |");
    out.push("|---|---|---|---|---|");
    for (const p of rls) {
      out.push(`| \`${esc(p.policyname)}\` | ${esc(p.cmd)} | ${esc(p.roles)} | \`${esc(p.using_expr) || "—"}\` | \`${esc(p.check_expr) || "—"}\` |`);
    }
  }

  // Indexes
  const idx = await q(`
    select indexname, indexdef
      from pg_indexes
     where schemaname='public' and tablename='${t.table_name}'
       and indexname not like '%_pkey'
     order by indexname
  `);
  if (idx.length) {
    out.push("\n**Indexes**");
    for (const i of idx) {
      out.push(`- \`${i.indexname}\`: \`${esc(i.indexdef)}\``);
    }
  }

  // Replica identity (only call out non-default)
  const ri = await q(`
    select relreplident from pg_class c
    join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relname='${t.table_name}'
  `);
  if (ri[0]?.relreplident && ri[0].relreplident !== "d") {
    const map = { d: "default (PK)", n: "nothing", f: "**FULL**", i: "index" };
    out.push(`\n**Replica identity:** ${map[ri[0].relreplident] ?? ri[0].relreplident}`);
  }

  out.push("");
}

// ── Views ──────────────────────────────────────────────────────────
console.log("Views...");
const views = await q(`
  select table_name, view_definition
    from information_schema.views
   where table_schema='public'
   order by table_name
`);
if (views.length) {
  out.push("\n## Views\n");
  for (const v of views) {
    out.push(`### \`${v.table_name}\``);
    out.push("```sql");
    out.push((v.view_definition || "").trim());
    out.push("```\n");
  }
}

// ── Functions ──────────────────────────────────────────────────────
console.log("Functions...");
const fns = await q(`
  select p.proname,
         pg_get_function_arguments(p.oid) as args,
         pg_get_function_result(p.oid) as result,
         p.prosecdef as security_definer,
         l.lanname as lang
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    join pg_language l on l.oid = p.prolang
   where n.nspname = 'public'
   order by p.proname
`);
if (fns.length) {
  out.push("\n## Functions / RPCs\n");
  out.push("| Name | Args | Returns | Lang | SECURITY DEFINER |");
  out.push("|---|---|---|---|---|");
  for (const f of fns) {
    out.push(`| \`${esc(f.proname)}\` | \`${esc(f.args)}\` | \`${esc(f.result)}\` | ${esc(f.lang)} | ${f.security_definer ? "✓" : ""} |`);
  }
}

// ── Triggers ──────────────────────────────────────────────────────
console.log("Triggers...");
const trigs = await q(`
  select event_object_table as tbl, trigger_name, event_manipulation, action_timing, action_statement
    from information_schema.triggers
   where trigger_schema='public'
   order by event_object_table, trigger_name
`);
if (trigs.length) {
  out.push("\n## Triggers\n");
  out.push("| Table | Trigger | When | Statement |");
  out.push("|---|---|---|---|");
  for (const t of trigs) {
    out.push(`| \`${esc(t.tbl)}\` | \`${esc(t.trigger_name)}\` | ${esc(t.action_timing)} ${esc(t.event_manipulation)} | \`${esc(t.action_statement)}\` |`);
  }
}

// ── Realtime publication ──────────────────────────────────────────
console.log("Realtime publication...");
const pub = await q(`
  select tablename
    from pg_publication_tables
   where pubname='supabase_realtime' and schemaname='public'
   order by tablename
`);
if (pub.length) {
  out.push("\n## Realtime publication\n");
  out.push("Tables included in `supabase_realtime` (clients receive INSERT/UPDATE/DELETE events, RLS enforced):\n");
  for (const r of pub) out.push(`- \`${r.tablename}\``);
}

// ── Migrations applied ──────────────────────────────────────────
console.log("Migrations log...");
try {
  const migs = await q(`
    select name, applied_at
      from public._ikratom_migrations
     order by applied_at desc
     limit 20
  `);
  if (migs.length) {
    out.push("\n## Recent migrations\n");
    out.push("| Migration | Applied |");
    out.push("|---|---|");
    for (const m of migs) out.push(`| \`${esc(m.name)}\` | ${esc(m.applied_at)} |`);
  }
} catch {
  // _ikratom_migrations may not exist on fresh envs; skip silently
}

writeFileSync(OUT, out.join("\n") + "\n");
console.log(`✓ wrote ${OUT}`);
