-- ============================================================
-- 0061_bill_journey
--
-- Cumulative-narrative fields for bills that have undergone
-- amendments. The existing summary_ai is a 2-sentence snapshot of
-- the LATEST version (good for list cards). On the bill detail page
-- we want to convey the FULL trajectory:
--   - what the bill originally proposed when introduced
--   - what each major amendment changed
--   - where the bill stands now operationally
--   - cumulative impact on advocates
--
-- Generated by scripts/enrich-bill-journey.mjs which feeds OpenStates
-- versions[] + actions[] + each version's PDF text into the AI router.
--
-- amendments_count: how many distinct version snapshots OpenStates
-- exposes for this bill (introduced + each amendment / committee
-- substitute / engrossment / enrollment). Used by the page to decide
-- whether to render the journey block at all (>= 2 versions = render).
-- ============================================================

alter table public.bills
  add column if not exists journey_narrative text,
  add column if not exists amendments_count integer,
  add column if not exists journey_analyzed_at timestamptz;

-- Index so we can quickly find bills that need re-analysis after a
-- new sync brings in a new version (cron: re-analyze any bill where
-- last_synced_at > journey_analyzed_at).
create index if not exists ix_bills_journey_stale
  on public.bills (journey_analyzed_at)
  where journey_narrative is not null;
