-- ============================================================
-- 0063_bill_substance_targeting
--
-- Replaces the binary targets_natural_leaf / targets_synthetic_only
-- columns with a structured per-substance map. The current binary
-- model can't distinguish:
--
--   - "bans synthetic + scheduling 7-OH" (NH SB 557 amendment 1798h)
--   - "restricts only retailers selling 7-OH-enriched products"
--     (NH SB 557 House version)
--
-- Both come back as targets_synthetic_only=true under the old schema,
-- losing critical scope detail.
--
-- New schema: bills.substance_targeting jsonb keyed by substance class.
-- Each substance gets a row with a tri-state stance + scope qualifier
-- + confidence. Substance classes:
--
--   natural_leaf    — Whole-leaf kratom prepared by traditional methods
--                     (heat, water/ethanol extraction). The plant.
--   mitragynine     — Mitragynine (MGM), the dominant natural alkaloid
--                     (~1-2% of leaf weight). Includes purified MGM.
--   seven_oh        — 7-hydroxymitragynine (7-OH). Natural trace alkaloid
--                     (~0.04% in fresh leaf). Distinct from semi-
--                     synthetic concentrates above natural levels.
--   pseudoindoxyl   — Mitragynine pseudoindoxyl ("pseudo"). Oxidation
--                     metabolite, much higher opioid affinity than MGM.
--                     Often produced semi-synthetically.
--   synthetic       — Any lab-synthesized or biosynthetically produced
--                     kratom alkaloid (recombinant, yeast-driven, etc.)
--                     regardless of which alkaloid.
--
-- Per-substance shape:
--   {
--     "stance": "bans" | "restricts" | "schedules" | "preserves" | "neutral" | "unaddressed",
--     "scope":  "statewide" | "retail_only" | "specific_retailer" | "research_exempt" | null,
--     "schedule": "I" | "II" | "III" | "IV" | "V" | null,
--     "confidence": 0.00 - 1.00,
--     "notes": "free-text qualifier"
--   }
--
-- Old binary columns retained for back-compat reads but deprecated;
-- the page will prefer substance_targeting when present.
-- ============================================================

alter table public.bills
  add column if not exists substance_targeting jsonb,
  add column if not exists substance_targeting_analyzed_at timestamptz;

-- GIN index so we can query "all bills that ban 7-OH" without
-- pulling everything client-side.
create index if not exists ix_bills_substance_targeting
  on public.bills using gin (substance_targeting jsonb_path_ops);

-- Convenience: quick filter for "this bill addresses 7-OH at all"
create or replace function public.bill_addresses_substance(
  bill_row public.bills,
  substance text
) returns boolean
language sql
immutable
as $$
  select bill_row.substance_targeting ? substance
     and (bill_row.substance_targeting -> substance ->> 'stance') is distinct from 'unaddressed';
$$;

comment on column public.bills.substance_targeting is
  'Per-substance stance map. Keys: natural_leaf | mitragynine | seven_oh | pseudoindoxyl | synthetic. Each value: {stance, scope, schedule, confidence, notes}. Generated by enrich-bill-journey.mjs.';
