-- ============================================================
-- 0064_bill_full_text_and_summary
--
-- Two additions to bills:
--
-- 1. bill_text_versions — jsonb array of every version's full
--    extracted text + provenance. Lets /bills/[id] render the actual
--    bill text on the iKratom site instead of redirecting to the
--    state portal. Each version: {label, date, text, source_url}.
--
-- 2. summary_long — a 200-300 word substantive summary, FastDemocracy-
--    grade. The existing summary_ai is a 2-sentence headline; this is
--    the paragraph-form prose that explains what the bill does, how
--    it works, what it changes, and what its fiscal/operational
--    impact is.
--
-- Storage cost is reasonable: ~5-30KB per version, 5-10 versions per
-- bill, ~62 active 2026 bills = under 10MB total. Supabase free-tier
-- DB is 500MB; we're well within budget.
-- ============================================================

alter table public.bills
  add column if not exists bill_text_versions jsonb,
  add column if not exists summary_long text,
  add column if not exists text_synced_at timestamptz;

-- Generated full-text-search column over bill_text_versions content.
-- Lets /bills?q=... or future global search hit the actual bill body,
-- not just title/summary. tsvector concat of the latest version's text
-- + title + summary_long.
alter table public.bills
  add column if not exists fulltext_tsv tsvector
  generated always as (
    setweight(to_tsvector('english', coalesce(title, '')), 'A')
    || setweight(to_tsvector('english', coalesce(summary_long, '')), 'B')
    || setweight(to_tsvector('english', coalesce(summary_ai, '')), 'B')
    || setweight(to_tsvector('english',
        coalesce(
          (bill_text_versions -> -1 ->> 'text'),
          ''
        )
      ), 'C')
  ) stored;

create index if not exists ix_bills_fulltext_tsv
  on public.bills using gin (fulltext_tsv);

comment on column public.bills.bill_text_versions is
  'jsonb array of every version''s extracted text. Each: {label, date, text, source_url}. Latest version is the last element. Populated by enrich-bill-journey.mjs.';
comment on column public.bills.summary_long is
  '200-300 word substantive summary, FastDemocracy-grade. Generated by enrich-bill-journey.mjs alongside the journey narrative.';
