-- 0110: Per-state advocacy briefings.
--
-- A briefing is an AI-synthesized field-work guide for one state. It
-- pulls together everything the advocate needs to know to take action
-- on kratom policy in their state: legislative landscape, BoP status,
-- key reps to contact, capital info, news context, and tactical advice.
--
-- One ACTIVE briefing per state at a time; regenerations replace via
-- a swap (set old.is_active = false in same txn as inserting new).
-- Older inactive rows kept for diffing + audit.
--
-- The body_md is AI-generated markdown, rendered via the existing
-- /briefings infrastructure. data_snapshot keeps the raw stats fed
-- to the AI so we can detect when regeneration would meaningfully
-- change the briefing (avoid spending tokens on no-data-change days).
--
-- Rollback:
--   DROP POLICY ... ON state_briefings;
--   ALTER TABLE state_briefings DISABLE ROW LEVEL SECURITY;
--   DROP TABLE state_briefings;

CREATE TABLE IF NOT EXISTS state_briefings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- 2-letter state code (NY, FL, etc.), 'FED' for federal-only, 'ALL' for cross-state
  state text NOT NULL,
  body_md text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  generated_by_provider text,                  -- 'gemini' / 'groq' / 'cerebras' / 'manual'
  generation_cost_cents int,
  data_snapshot jsonb,                          -- raw stats fed to AI (audit + regen-comparison)
  is_active boolean NOT NULL DEFAULT true,
  -- Hand-edited override block — admin can fold in tactical content
  -- the AI can't generate (e.g. specific allies' phone numbers, exact
  -- talking points that worked in the last hearing). Prepended to body_md
  -- at render time. NULL = no override.
  manual_addendum_md text,
  notes text
);

-- Only one ACTIVE briefing per state at a time.
CREATE UNIQUE INDEX IF NOT EXISTS ux_state_briefings_active
  ON state_briefings (state)
  WHERE is_active = true;

-- Fast retrieval for the public page
CREATE INDEX IF NOT EXISTS ix_state_briefings_state_gen
  ON state_briefings (state, generated_at DESC);

COMMENT ON TABLE state_briefings IS
  'AI-synthesized field-work briefings, one per state. Generated by scripts/generate-state-briefing.mjs daily. See /briefings/state/[code].';
COMMENT ON COLUMN state_briefings.data_snapshot IS
  'Raw stats fed to AI (bill counts, news recency, etc.) — used by the generator to skip regeneration when nothing changed.';
COMMENT ON COLUMN state_briefings.manual_addendum_md IS
  'Admin-curated tactical guidance prepended to AI body at render time. For talking points, ally contacts, hearing tips.';

-- RLS: world-readable (briefings are public advocacy content), admin write.
ALTER TABLE state_briefings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read active briefings" ON state_briefings;
CREATE POLICY "Public read active briefings"
  ON state_briefings FOR SELECT
  USING (is_active = true);

DROP POLICY IF EXISTS "Admin write briefings" ON state_briefings;
CREATE POLICY "Admin write briefings"
  ON state_briefings FOR ALL
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));
