-- 0207_news_digest.sql
--
-- "iKratom links should BE the destination." Today /news/[id] shows a 2-3
-- sentence AI summary + a fair-use lead excerpt (when extraction succeeds) +
-- the publisher's embedded media, then links out. When extraction fails
-- (paywall / JS-rendered / robots-blocked) the page is thin and the browser
-- "Listen" has only a headline to read — so users bounce to the source.
--
-- This adds an ORIGINAL, copyright-safe full write-up ("digest") generated by
-- the free-tier AI router from whatever real source text we already have (the
-- fair-use excerpt / verification snippet). It is OUR neutral synthesis, not
-- the publisher's text — so it can be the complete on-page read AND the Listen
-- body. generate-news-digest.mjs only writes a digest when real source text
-- exists (never from a bare headline) so we never fabricate a story.
--
--   digest_paragraphs:   jsonb array of plain-text paragraph strings (capped).
--   digest_generated_at: when the digest was produced (NULL = not yet, or no
--                        source text available to synthesize from).
--
-- Also fixes a silent-failure trap in extract-news-content.mjs: a page that
-- fetched OK but yielded zero paragraphs used to stamp body_extracted_at and
-- was then never retried. body_extract_attempts lets the extractor retry a
-- bounded number of times (e.g. a headless render may succeed on a later run)
-- before giving up — so transiently-broken sources self-heal instead of dying
-- empty forever.
--
-- FOLLOW-UP (not in this migration): #624's search_tsv generated column
-- (mig 0206) indexes body_paragraphs but not digest_paragraphs. Once both land,
-- a later migration should fold digest_paragraphs into search_tsv so the
-- in-app write-up is full-text searchable too.
--
-- Rollback: drop the three columns.

ALTER TABLE public.news_items
  ADD COLUMN IF NOT EXISTS digest_paragraphs jsonb,
  ADD COLUMN IF NOT EXISTS digest_generated_at timestamptz,
  ADD COLUMN IF NOT EXISTS body_extract_attempts integer NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.news_items.digest_paragraphs IS
  'Original AI digest: jsonb array of plain-text paragraphs synthesized by the free-tier router from real source text (fair-use excerpt). OUR neutral write-up, not the publisher body — safe to render in full + read aloud. NULL = no digest yet (no source text to synthesize from).';
COMMENT ON COLUMN public.news_items.digest_generated_at IS
  'When generate-news-digest.mjs produced digest_paragraphs. NULL = not yet processed or no source text available.';
COMMENT ON COLUMN public.news_items.body_extract_attempts IS
  'How many times extract-news-content.mjs has fetched this article and found zero paragraphs. Bounded retry: once it succeeds (body_extracted_at set with paragraphs) or the cap is hit, retries stop.';
